language: java
matrix:
  include:
  - os: linux
    jdk: openjdk8
  - os: linux
    jdk: openjdk9
  - os: linux
    jdk: openjdk10
  - os: linux
    jdk: openjdk11
  - os: linux
    jdk: openjdk12
  - os: osx
    osx_image: xcode8.3
    jdk: oraclejdk8
  - os: osx
    osx_image: xcode8.3
    jdk: openjdk9
  - os: osx
    osx_image: xcode8.3
    jdk: openjdk10
  - os: osx
    osx_image: xcode8.3
    jdk: oraclejdk11
  - os: osx
    osx_image: xcode8.3
    jdk: openjdk12
before_install:
- npm config delete prefix
install:
- if [[ $TRAVIS_OS_NAME == 'linux' ]]; then bash ./.travis/install-linux.sh ; fi
- if [[ $TRAVIS_OS_NAME == 'osx' ]]; then bash ./.travis/install-os.sh; fi
- cd $TRAVIS_BUILD_DIR
- eval "$(gimme 1.11)"
script:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
- make test
before_deploy:
- make package
deploy:
  provider: releases
  api_key:
    secure: TrAKKu8oG0ydGHerVzsTGiPg76/f0m/7RvcuDHiEWSZRepb84P2R/ZBBQAE6XvGLl3/+KpJlszODE4ARqwC23mWA8o00viu9s44nveK3Scuzch8TumuLpTiIcAxqcgwSZUL0fXJWHLWEdb5MwEnv73a8j+ginjLXWmou/wgTAqyNvbuv3OnktncNSa5Px3A+jWgkmFyjnhSovrTXPxT1s2NdutrEkXbavXHeZy651ciSMjaspFnSIe7fgI/BcK86z1HtyeGwbG67Rx+kVwXuFL9hJLRqtGkLojGLojmwyJeC2JL50Qkva+AUurTSXCwWBCq4Ih/ooB/aR9L+Q3liR5E2fIpEayLypnL1vvThomrF2OdBATSzXKX1zoxALIqGsbQEWZbdhRMrw24+ZTPfncj9OBDVe/KGreUov+QVOadhPN8j+wbKJIq7DWlsU+qQ/UEjDbVYbW7rZXyWF0voyWNIdsLYDaUvTVnHmB14BcM5A2NZpwWBllJ5eZ5S3y4wyOKIQC1evl7ZgjLNoymObMR2Wyh3UiEOn4r+VixOBOWunoz8BGNFYtxwNX5Fh1okRnxf9dH+/W/e6+vLU2DzWuYUBtRzkFUNvJcHitbZ6OZBzW/isMXQxUc3laCK0J7EugmNBRjV7AM66/laEhTh87Q1PSwbDmrxjtnjkdcki/o=
  file: 
  - "./lib/skyapi/target/skyapi-${TRAVIS_TAG}.jar"
  - "./target/libskycoin-java-${TRAVIS_TAG}.jar"
  on:
    repo: simelo/libjava-skycoin
    tags: true
notifications:
  email: false
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
