language: java
matrix:
  include:
  - os: linux
    jdk: openjdk8
  - os: linux
    jdk: openjdk9
  - os: linux
    jdk: openjdk10
  - os: linux
    jdk: openjdk11
  - os: linux
    jdk: openjdk12
  - os: osx
    osx_image: xcode8.3
    jdk: oraclejdk8
  - os: osx
    osx_image: xcode8.3
    jdk: openjdk9
  - os: osx
    osx_image: xcode8.3
    jdk: openjdk10
  - os: osx
    osx_image: xcode8.3
    jdk: oraclejdk11
  - os: osx
    osx_image: xcode8.3
    jdk: openjdk12
before_install:
- npm config delete prefix
install:
- if [[ $TRAVIS_OS_NAME == 'linux' ]]; then bash ./.travis/install-linux.sh ; fi
- if [[ $TRAVIS_OS_NAME == 'osx' ]]; then bash ./.travis/install-os.sh; fi
- cd $TRAVIS_BUILD_DIR
- eval "$(gimme 1.11)"
script:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
- make test
before_deploy:
- make package
deploy:
  provider: releases
  api_key:
    secure: rQNiLbLZn3K7JK4bIn0U4rXdxV6EN+HzBll2LOoWRV8Vl22jXMJJ33pS78T7ulXyIGyDuNZPFW0A1OwxrCdfjh6eM7SKDRrPDZcBcoLVdtM65tuLB1uaxRD5IU2LRCpAkiQXhLydMhMlc5HmzL1lDM4mtm889+oRUyLc3d4RSLu+k46Wbv7QvUK3ZNUIrcLJ6AppAqVneXntEGJ4iHtmt4XMQYN4SE9TNSCDuAQL3TygCRDQvqY5uT3fJ19wGnanVfx5HA2LKlulHvO5SDVakM0u+IrEMvhrEVN6X00rs6chn6zbVHvAKYzW63YLcSirF6Q7YCAMB5gJkMsj698LUAzVySrVBSlIbMIGKluVKtzF0VHlQTxqrFbJb3o+qsxNkox/6WEhsopZmlX13FYGmNCa8MM8qqmcT0NqSTymnBvP9vNkwJZltH7V/Ul+wzBAMa5tsu2gyHupVpP16giCuopBDK5PNYqfZbRinswJoLY4OhdM1T9F2WZ8vrFgoRCnpTIOyUXoHOnJmK4RbrpmJh1LVedf8FtR4Rsku+A96Fs3b1gTccy4cKIo07LnmJfXgd+OSrfy4iZ98VDALHDPQbct5JRwcFS379MIXi9xFZfrLHQgglVAMHmr+EGB7Tmhk5vgIc769E1Bab7RCrN6ZVbm7HKNx0MpR0CM5VljX4M=
  file:
  - "./lib/skyapi/target/skyapi-$(echo ${TRAVIS_TAG} | cut -d'v' -f 2).jar"
  - "./target/libskycoin-java-$(echo ${TRAVIS_TAG} | cut -d'v' -f 2).jar"
  skip_cleanup: true
  on:
    repo: simelo/libjava-skycoin
    tags: true
notifications:
  email: false
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
