language: java

matrix:
  include:
    - os: linux
      jdk: oraclejdk8
    - os: linux
      jdk: oraclejdk9
    - os: linux
      jdk: openjdk8
    - os: linux
      jdk: openjdk9
    - os: osx
      osx_image: xcode9.3
      jdk: oraclejdk8
    - os: osx
      osx_image: xcode9.4
      jdk: oraclejdk11

install:
  - eval "$(gimme 1.11)"
  - go version
  - mkdir swig_build && cd swig_build && wget http://prdownloads.sourceforge.net/swig/swig-3.0.12.tar.gz && tar -zxf swig-3.0.12.tar.gz && cd swig-3.0.12 && sudo ./configure --prefix=/usr && sudo make && sudo make install && cd ../../ && sudo rm -rf swig_build	

script:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V 
  - make configure
  - make build-libc
  - make build-swig
  - make build-libjava
  - make test
  
notifications:
  email: false
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify
